language: swift
sudo: required
compiler: clang

matrix:
  include:
    - os: linux
      dist: trusty # Ubuntu 14.04 LTS
    - os: linux
      osx_image: xcode9.3beta

before_install:
  - uname -a
  - sudo echo "hello from sudo"
script:
  - echo "hello travis!"
